### ISSUE TITLE
Provider: Implement crypto-wallet-based authentication

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/nuxt-auth#467]
### Goal

Implement a wallet-based login.

### Context

On one of our engagements we needed to implement authentication using chain-wallets. We would love to transfer it to this project to offer the same functionality to Nuxt 3 users for an easy entry into the crypto-space.

Providers in `nuxt-auth` generally have two components:
- client-side functionality
  - `authjs` provider: https://github.com/sidebase/nuxt-auth/tree/main/src/runtime/composables/authjs
  - `local` provider: https://github.com/sidebase/nuxt-auth/tree/main/src/runtime/composables/local
- server-side functionality
  - `authjs` provider: https://github.com/sidebase/nuxt-auth/tree/main/src/runtime/server/services/authjs
  - `local` provider: Not applicable, this could be any backend that provides username & password based flows. A reference implementation using nuxt 3 can be found here: https://github.com/sidebase/nuxt-auth/tree/main/playground-local/server/api/auth

For our implementation here client-only + a reference server-side implementation should be sufficient. Later on we can think about providing server-side utilities, but that will also force us to think about default ways to specify DB-adapters and more.

Based on this scope-limitation using the `local` provider as an implementation example should be most helpful. Another interesting resource: @danielwinkelmann started on an implementation of a `refresh` provider in #373. The refresh provider is very similar to the `local` provider with the addition of a periodic token-refresh.

Other notes:
- Add all documentation into the `docs/v0.6/` folder -> this feature will only be supported by the new v0.6 
- All dependencies that are provider-specific:
  - should be added as peer dependencies
  - should be documented as provider specfic setup on the installation page (e.g., see https://sidebase.io/nuxt-auth/v0.6/getting-started/installation for `local` and `authjs` already documented)
- don't forget to document new configuration you add

### Assets

Related issue + implementation of ethereum based authentication: https://github.com/powerhouse-inc/switchboard-boilerplate/issues/52

### Tasks

- [ ] Ask any questions that arise
- [ ] Implement the provider
- [ ] Implement a playground for the provider + instructions on how to use

**Comment by valiafetisov** [comment]
Looking at the linked composables I don't think most of those (sign in, sign out, token management, etc) needs to be reimplemented in order to support "Sign-In with Ethereum" functionality. I would instead contribute a smaller abstraction (e.g. adapter/integration/provider, not sure what's the vocabulary here) – a relatively small part of code:
- a function/endpoint to generate a challenge (message that needs to be signed)
- a function/endpoint to validate the challenge (checks signature and other security-related parts)
- maybe extra frontend helper to trigger the browser extension and call endpoints (i.e. web-based wallet)

And I imagine that if it's just a provider, it can even live in a different repo/example implementation. 

Do you see a technical/organisational problem with what I've described?

**Comment by BracketJohn** [comment]
> Do you see a technical/organisational problem with what I've described?

Not at all! Proposal: Add a new `playground-ethereum/` folder by cope-pasting the `local` playground. Then you have the freedom to in parallel:
- work on a reference / example implementation inside the `playground-ethereum/` folder
- apply any required module changes directly to the module code

In the end we'll have a full picture of what complexity stays on the users' app-side and what complexity will be moved into the module.

In the future or right in that PR we can then also discuss & move the balance of this abstraction further into the module or into the users' app.
