### ISSUE TITLE
Setup deployment of the docs page

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/nuxt-auth#53]
**Goal**
In order to improve our DX, we want to publish are own extensive docs page. The docs have already been created in https://github.com/sidebase/docs and need to be transferred into the respective module repositories. 
Afterwards we hope to host each documentation with GitHub Pages, allowing them to be redeployed after every merge to the main branch. 

In order to do this we first need to check how we can correctly assign subdomains to a specific github page. In this case we want to use the subdomain https://nuxt-auth.sidebase.io to publish our docs. 

As far as I see, we just need to add a CNAME record for all subdomains of sidebase.io to point to the GitHub servers. Once done, we can verify the subdomain through the GitHub verification process to provide proof of ownership. 

**Links**
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages
https://sean-coughlin.medium.com/how-to-host-a-site-with-a-subdomain-on-github-pages-33202341f711

**Tasks**

- [ ] Finish documentation (@zoey-kaiser for finishing, @BracketJohn for review)
- [ ] Setup CNAME record for the domain (@IronicUsername)
- [ ] Add documentation folder to `nuxt-auth` repo (@zoey-kaiser)
- [ ] Setup Github Actions to rebuild docs so we do not need to do it manually (optional, depending on how much extra work it presents, @IronicUsername)

**Comment by BracketJohn** [comment]
>  Setup CNAME record for the domain (@IronicUsername)

as discussed, let's do this all on the central `sidebase.io` domain
