### ISSUE TITLE
0.6.0 release checklist

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/nuxt-auth#565]
Before npm release:

- [x] prepare docs (https://github.com/sidebase/nuxt-auth/pull/566 & https://github.com/sidebase/docs/pull/149)
  - [x] Make NuxtAuth 0.6.0 the default version
  - [x] Make NuxtAuth 0.5.0 docs show that it is an older version
  - [x] Add an annoucement banner to foward to the release notes
  - [ ] <del>Attempt to upgrade docs to a newer nuxt version for better performance</del> (https://github.com/sidebase/docs/pull/149#issuecomment-1808117514)
- [X] finish nuxtauth example PR to update to version 0.6 (https://github.com/sidebase/nuxt-auth-example/pull/31)
- [X] prepare release annoucement for twitter and discord (s1)

After npm release:
- [x] Merge docs PR
- [x] Merge NuxtAuth example PR
- [x] Prepare release notes
- [x] Post Twitter and discord annoucement

s1:
![sidebase 0 6 0 release](https://github.com/sidebase/nuxt-auth/assets/30908158/8430f4e4-f3f0-47d9-9070-b950c09884d5)

**Comment by BracketJohn** [comment]
seems good to me, thanks!

**Comment by zoey-kaiser** [comment]
Released in https://github.com/sidebase/nuxt-auth/releases/tag/0.6.0
